### ISSUE TITLE
TypeError when using g.bootstrap

### ISSUE THREAD

**Issue by alvarocalderon** [PrincetonUniversity/gerrymandertests#1]
I'm trying to use Wang's 3 tests. However, when trying to use Test 1 (the excess seats test), I get the following errors:
`KeyError: 'bootstrap'`
`TypeError: object of type 'numpy.float64' has no len()`

Code to replicate the error:
```
impute_val = 1
chambers = defaultdict(lambda: defaultdict(list))
chambers['Congressional']['filepath'] = 'election_data/congressional_election_results_post1948.csv'

metric_dict = {'bootstrap': g.bootstrap,
               't_test_diff':            g.t_test_diff,
               'mean_median_diff':       g.mean_median}
for chamber in chambers:
    chambers[chamber]['elections_df'] = g.parse_results(chambers[chamber]['filepath'])
    chambers[chamber]['tests_df'] = g.tests_df(g.run_all_tests(
        chambers[chamber]['elections_df'],
        impute_val=impute_val,
        metrics=metric_dict))
```

I'm using Python 3.6. 
I guess the error may come from this part of the function 'bootstrap', but I'm not sure how to solve it:
`n_matches = len(match_seats)`

Is it also possible that I'm using the function incorrectly. I would appreciate any help!

Update: I also got the same error when using g.t_test and g.mean_median_test.

**Comment by wtadler** [comment]
Sorry about this. [A few](https://github.com/PrincetonUniversity/gerrymandertests/blob/master/gerrymetrics/metrics.py) of the metric functions (`bootstrap`, `t_test`, `mean_median_test`, and others) return dictionaries rather than scalars so can't be used like this. If you want the results dictionaries from those functions (which include p-values and the like), you'll have to call those directly rather than with the convenience functions in the example.
